---
dist: xenial
language: python
matrix:
  include:
    - name: lang-it
      env: >
        LANG=it
        PACKAGES="hunspell-it witalian"
        HUNSPELL_LANG=it_IT
        WL_PATH=/usr/share/dict/italian

    - name: lang-en
      env: >
        LANG=en
        PACKAGES="hunspell-en-gb wbritish-huge"
        HUNSPELL_LANG=en_GB
        WL_PATH=/usr/share/dict/british-english-huge

    - name: lang-es
      env: >
        LANG=es
        PACKAGES="hunspell-es wspanish"
        HUNSPELL_LANG=es_ES
        WL_PATH=/usr/share/dict/spanish

# XXX: suspended
#    - name: lang-fr
#      env: >
#        LANG=fr
#        HUNSPELL_PACKAGE=hunspell-fr-comprehensive
#        ASPELL_PACKAGE=aspell-fr
#        DICT_PACKAGE=wfrench
#        HUNSPELL_LANG=fr_FR
#        ASPELL_LANG=fr
#        WL_PATH=/usr/share/dict/french

if: branch != master or tag =~ /^v\d+$/
python:
  - '3.6'
before_install:
  - sudo apt-get install hunspell-tools aspell $PACKAGES
  - pip install pipenv
install:
  - pipenv install --three
script:
  - >
    ( cat $WL_PATH;
    unmunch
    /usr/share/hunspell/$HUNSPELL_LANG.dic
    /usr/share/hunspell/$HUNSPELL_LANG.aff
    2>/dev/null | iconv -f iso-8859-15 -t utf-8 -
    ) | tools/build.py
    --pool-size 2
    --output wordlist-$LANG.marisa
  - ls -las
deploy:
  provider: releases
  api_key:
    secure: >
      GuekFIW1gZSXied6IPID6bIMyTSk4KZgE60aVmSzoKcwergKHVoHkMvAZMcWSqM6+5qg\
      wgR1Uwro8xgT7pcEboAERExb/71xS7SUo3gsEJNp5/ehYGa5VxgnamgrTKjHtiBb2Oy6\
      5dCBGMN8h55wzd/lr7YKbOAF/vn1H5ATelgq79Zv3EPAvQUFn6IlcST0lQfs93xPE0F3\
      4iulHuss+bIuO4ImKEwjWoNTj656ffM1dTyug5iryuA2OT+wwJS3xTC7ICswU0iRPOjA\
      THHHZsYTBaeB6ZH6KDvVpxt0j2NQKtzrKhT5gEdXqeg8a9ZxxPBZAjLEBNbm0tK/6xL+\
      jsHsntUicsLlw+LxaXv4oxU5G2TUJBZaeehJf1sVWDUcLrOcPavgfWlA3a1/wSuonAuA\
      nRdx+GBcnbywwljBxu9riUiEqApUnOXTU3/+nNPXJXEyWr5hSzRQmzG1OMBs0gH+/5Zq\
      K6srWkEZle+ugjg/hUjU4YW0hYXRMQUbwZcB7im6Kyp+eu7ZwCtJV9Ek+/EXd4nyMjBu\
      8vlbHFoshSf02ryn5CnIwb0SkTZzMzronGmJlYD8XNo/uz7i6HDIY97uKjF/rLmH5CSW\
      fDfxjrs3Dt3kcUrEDHwURs9/ZIn63QwlQH4rHds7O1tovBziuB7+9MIwpDSyuhrYRbvI\
      9Z8=
  file: wordlist-$LANG.marisa
  skip_cleanup: true
  on:
    repo: aogier/tries
    tags: true
